name: sudoku
description: "Sudoku Game"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sudoku_dart: ^1.1.0
  icons_plus: ^4.0.0
  flutter_animate: ^4.3.0
  fluttertoast: ^8.2.4
  hive: ^2.2.3
  sudoku_solver_generator: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
